import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    env: {
      NEXT_PUBLIC_USE_MOCK_API: "true",
    },
    include: ["**/*.{test,spec}.ts"],
    exclude: ["**/node_modules/**", "**/e2e/**", "**/.next/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary"],
      include: [
        "lib/**/*.ts",
        "mocks/**/*.ts",
        "features/explore/map-route.ts",
        "features/home/search-schema.ts",
        "features/itinerary/mock-data.ts",
        "app/api/v1/search/places/route.ts",
      ],
      exclude: [
        "**/*.test.ts",
        "**/*.spec.ts",
        "**/e2e/**",
        "lib/itinerary-pdf.ts",
        "lib/routes.ts",
        "lib/auth/get-session.ts",
        "lib/auth/handle-trip-live.ts",
        "lib/auth/profile-upload-live.ts",
        "lib/auth/adapter.ts",
        "lib/community/adapter.ts",
        "lib/social/adapter.ts",
        "lib/offline/private-cache.ts",
        "lib/pwa/**",
        "lib/realtime/dolan-socket.ts",
        "lib/auth/handle-auth.ts",
        "lib/auth/handle-profile.ts",
        "lib/auth/handle-trip.ts",
        "lib/template-itinerary.ts",
        "lib/route-travel.ts",
        "lib/route-optimize.ts",
        "lib/realtime/chat-format.ts",
        "lib/realtime/chat-status.ts",
        "mocks/joins.ts",
        "lib/social/handle-social.ts",
        "lib/community/handle-community.ts",
        "lib/auth/trip-map.ts",
        "mocks/auth.ts",
        "mocks/profile.ts",
        "lib/destination-itinerary.ts",
        "lib/itinerary-stop-view.ts",
        "lib/domiciles.ts",
        "mocks/trips.ts",
        "mocks/social.ts",
        "mocks/geo.ts",
        "mocks/community-store.ts",
        "features/itinerary/trip-itinerary-store.ts",
        "lib/destination-cover.ts",
        "features/explore/map-route.ts",
      ],
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "."),
      "@dolan/shared": path.resolve(__dirname, "../shared/src/index.ts"),
    },
  },
});
