export const AuthErrorCode = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  PROFILE_INCOMPLETE: "PROFILE_INCOMPLETE",
  EMAIL_UNVERIFIED: "EMAIL_UNVERIFIED",
  ACCOUNT_RESTRICTED: "ACCOUNT_RESTRICTED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  NOT_MEMBER: "NOT_MEMBER",
  NOT_HOST: "NOT_HOST",
  PENDING_MEMBER: "PENDING_MEMBER",
  INVALID_TOKEN: "INVALID_TOKEN",
} as const;

export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];
