export const AuthErrorCode = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  PROFILE_INCOMPLETE: "PROFILE_INCOMPLETE",
  EMAIL_UNVERIFIED: "EMAIL_UNVERIFIED",
  ACCOUNT_RESTRICTED: "ACCOUNT_RESTRICTED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  NOT_MEMBER: "NOT_MEMBER",
  NOT_HOST: "NOT_HOST",
  PENDING_MEMBER: "PENDING_MEMBER",
  INVALID_TOKEN: "INVALID_TOKEN",
  JOB_ALREADY_ACTIVE: "JOB_ALREADY_ACTIVE",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
  INVALID_GENERATION: "INVALID_GENERATION",
} as const;

export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];

export const SearchErrorCode = {
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
  INVALID_FILTER: "INVALID_FILTER",
  INVALID_CITY: "INVALID_CITY",
  TEMPLATE_UNAVAILABLE: "TEMPLATE_UNAVAILABLE",
  INVALID_PLAN_INPUT: "INVALID_PLAN_INPUT",
  PLACE_NOT_FOUND: "PLACE_NOT_FOUND",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
} as const;

export type SearchErrorCode = (typeof SearchErrorCode)[keyof typeof SearchErrorCode];

export const TripErrorCode = {
  INVALID_DATE: "INVALID_DATE",
  INVALID_BUDGET: "INVALID_BUDGET",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  TRIP_FULL: "TRIP_FULL",
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",
  BLOCKED_RELATION: "BLOCKED_RELATION",
  INVALID_PARENT: "INVALID_PARENT",
  TRIP_NOT_PUBLIC: "TRIP_NOT_PUBLIC",
  TRIP_NOT_FOUND: "TRIP_NOT_FOUND",
  INVALID_FILTER: "INVALID_FILTER",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  INVALID_PLAN_INPUT: "INVALID_PLAN_INPUT",
} as const;

export type TripErrorCode = (typeof TripErrorCode)[keyof typeof TripErrorCode];
