export type DomicileKind = "Kota" | "Kabupaten" | "Jakarta";

type DomicileSeed = {
  kind: DomicileKind;
  name: string;
  province: string;
};

/** Kabupaten/kota for traveler domicile. Jakarta keeps the short label already stored on profiles. */
const SEEDS: DomicileSeed[] = [
  { kind: "Kota", name: "Banda Aceh", province: "Aceh" },
  { kind: "Kota", name: "Langsa", province: "Aceh" },
  { kind: "Kota", name: "Lhokseumawe", province: "Aceh" },
  { kind: "Kota", name: "Sabang", province: "Aceh" },
  { kind: "Kota", name: "Subulussalam", province: "Aceh" },
  { kind: "Kabupaten", name: "Aceh Besar", province: "Aceh" },
  { kind: "Kabupaten", name: "Aceh Utara", province: "Aceh" },
  { kind: "Kabupaten", name: "Aceh Tengah", province: "Aceh" },
  { kind: "Kabupaten", name: "Aceh Selatan", province: "Aceh" },
  { kind: "Kabupaten", name: "Bireuen", province: "Aceh" },
  { kind: "Kabupaten", name: "Pidie", province: "Aceh" },

  { kind: "Kota", name: "Medan", province: "Sumatera Utara" },
  { kind: "Kota", name: "Binjai", province: "Sumatera Utara" },
  { kind: "Kota", name: "Pematangsiantar", province: "Sumatera Utara" },
  { kind: "Kota", name: "Sibolga", province: "Sumatera Utara" },
  { kind: "Kota", name: "Tanjungbalai", province: "Sumatera Utara" },
  { kind: "Kota", name: "Tebing Tinggi", province: "Sumatera Utara" },
  { kind: "Kota", name: "Padang Sidempuan", province: "Sumatera Utara" },
  { kind: "Kota", name: "Gunungsitoli", province: "Sumatera Utara" },
  { kind: "Kabupaten", name: "Deli Serdang", province: "Sumatera Utara" },
  { kind: "Kabupaten", name: "Karo", province: "Sumatera Utara" },
  { kind: "Kabupaten", name: "Samosir", province: "Sumatera Utara" },
  { kind: "Kabupaten", name: "Langkat", province: "Sumatera Utara" },
  { kind: "Kabupaten", name: "Asahan", province: "Sumatera Utara" },
  { kind: "Kabupaten", name: "Labuhanbatu", province: "Sumatera Utara" },

  { kind: "Kota", name: "Padang", province: "Sumatera Barat" },
  { kind: "Kota", name: "Bukittinggi", province: "Sumatera Barat" },
  { kind: "Kota", name: "Padang Panjang", province: "Sumatera Barat" },
  { kind: "Kota", name: "Pariaman", province: "Sumatera Barat" },
  { kind: "Kota", name: "Payakumbuh", province: "Sumatera Barat" },
  { kind: "Kota", name: "Sawahlunto", province: "Sumatera Barat" },
  { kind: "Kota", name: "Solok", province: "Sumatera Barat" },
  { kind: "Kabupaten", name: "Agam", province: "Sumatera Barat" },
  { kind: "Kabupaten", name: "Tanah Datar", province: "Sumatera Barat" },
  { kind: "Kabupaten", name: "Lima Puluh Kota", province: "Sumatera Barat" },
  { kind: "Kabupaten", name: "Padang Pariaman", province: "Sumatera Barat" },

  { kind: "Kota", name: "Pekanbaru", province: "Riau" },
  { kind: "Kota", name: "Dumai", province: "Riau" },
  { kind: "Kabupaten", name: "Kampar", province: "Riau" },
  { kind: "Kabupaten", name: "Siak", province: "Riau" },
  { kind: "Kabupaten", name: "Bengkalis", province: "Riau" },
  { kind: "Kabupaten", name: "Pelalawan", province: "Riau" },
  { kind: "Kabupaten", name: "Rokan Hilir", province: "Riau" },
  { kind: "Kabupaten", name: "Indragiri Hilir", province: "Riau" },

  { kind: "Kota", name: "Jambi", province: "Jambi" },
  { kind: "Kota", name: "Sungai Penuh", province: "Jambi" },
  { kind: "Kabupaten", name: "Muaro Jambi", province: "Jambi" },
  { kind: "Kabupaten", name: "Batanghari", province: "Jambi" },
  { kind: "Kabupaten", name: "Bungo", province: "Jambi" },
  { kind: "Kabupaten", name: "Tebo", province: "Jambi" },

  { kind: "Kota", name: "Palembang", province: "Sumatera Selatan" },
  { kind: "Kota", name: "Lubuklinggau", province: "Sumatera Selatan" },
  { kind: "Kota", name: "Pagar Alam", province: "Sumatera Selatan" },
  { kind: "Kota", name: "Prabumulih", province: "Sumatera Selatan" },
  { kind: "Kabupaten", name: "Ogan Ilir", province: "Sumatera Selatan" },
  { kind: "Kabupaten", name: "Banyuasin", province: "Sumatera Selatan" },
  { kind: "Kabupaten", name: "Musi Banyuasin", province: "Sumatera Selatan" },
  { kind: "Kabupaten", name: "Lahat", province: "Sumatera Selatan" },
  { kind: "Kabupaten", name: "Muara Enim", province: "Sumatera Selatan" },

  { kind: "Kota", name: "Bengkulu", province: "Bengkulu" },
  { kind: "Kabupaten", name: "Bengkulu Tengah", province: "Bengkulu" },
  { kind: "Kabupaten", name: "Rejang Lebong", province: "Bengkulu" },
  { kind: "Kabupaten", name: "Kepahiang", province: "Bengkulu" },

  { kind: "Kota", name: "Bandar Lampung", province: "Lampung" },
  { kind: "Kota", name: "Metro", province: "Lampung" },
  { kind: "Kabupaten", name: "Lampung Selatan", province: "Lampung" },
  { kind: "Kabupaten", name: "Lampung Tengah", province: "Lampung" },
  { kind: "Kabupaten", name: "Lampung Timur", province: "Lampung" },
  { kind: "Kabupaten", name: "Lampung Utara", province: "Lampung" },
  { kind: "Kabupaten", name: "Pesawaran", province: "Lampung" },
  { kind: "Kabupaten", name: "Pringsewu", province: "Lampung" },
  { kind: "Kabupaten", name: "Tanggamus", province: "Lampung" },

  { kind: "Kota", name: "Pangkalpinang", province: "Kepulauan Bangka Belitung" },
  { kind: "Kabupaten", name: "Bangka", province: "Kepulauan Bangka Belitung" },
  { kind: "Kabupaten", name: "Bangka Tengah", province: "Kepulauan Bangka Belitung" },
  { kind: "Kabupaten", name: "Bangka Selatan", province: "Kepulauan Bangka Belitung" },
  { kind: "Kabupaten", name: "Belitung", province: "Kepulauan Bangka Belitung" },
  { kind: "Kabupaten", name: "Belitung Timur", province: "Kepulauan Bangka Belitung" },

  { kind: "Kota", name: "Batam", province: "Kepulauan Riau" },
  { kind: "Kota", name: "Tanjungpinang", province: "Kepulauan Riau" },
  { kind: "Kabupaten", name: "Bintan", province: "Kepulauan Riau" },
  { kind: "Kabupaten", name: "Karimun", province: "Kepulauan Riau" },
  { kind: "Kabupaten", name: "Lingga", province: "Kepulauan Riau" },
  { kind: "Kabupaten", name: "Natuna", province: "Kepulauan Riau" },
  { kind: "Kabupaten", name: "Kepulauan Anambas", province: "Kepulauan Riau" },

  { kind: "Jakarta", name: "Jakarta Pusat", province: "DKI Jakarta" },
  { kind: "Jakarta", name: "Jakarta Utara", province: "DKI Jakarta" },
  { kind: "Jakarta", name: "Jakarta Barat", province: "DKI Jakarta" },
  { kind: "Jakarta", name: "Jakarta Selatan", province: "DKI Jakarta" },
  { kind: "Jakarta", name: "Jakarta Timur", province: "DKI Jakarta" },
  { kind: "Kabupaten", name: "Kepulauan Seribu", province: "DKI Jakarta" },

  { kind: "Kota", name: "Bandung", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Bandung", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Bandung Barat", province: "Jawa Barat" },
  { kind: "Kota", name: "Banjar", province: "Jawa Barat" },
  { kind: "Kota", name: "Bekasi", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Bekasi", province: "Jawa Barat" },
  { kind: "Kota", name: "Bogor", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Bogor", province: "Jawa Barat" },
  { kind: "Kota", name: "Cimahi", province: "Jawa Barat" },
  { kind: "Kota", name: "Cirebon", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Cirebon", province: "Jawa Barat" },
  { kind: "Kota", name: "Depok", province: "Jawa Barat" },
  { kind: "Kota", name: "Sukabumi", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Sukabumi", province: "Jawa Barat" },
  { kind: "Kota", name: "Tasikmalaya", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Tasikmalaya", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Ciamis", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Cianjur", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Garut", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Indramayu", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Karawang", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Kuningan", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Majalengka", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Pangandaran", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Purwakarta", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Subang", province: "Jawa Barat" },
  { kind: "Kabupaten", name: "Sumedang", province: "Jawa Barat" },

  { kind: "Kota", name: "Semarang", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Semarang", province: "Jawa Tengah" },
  { kind: "Kota", name: "Surakarta", province: "Jawa Tengah" },
  { kind: "Kota", name: "Magelang", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Magelang", province: "Jawa Tengah" },
  { kind: "Kota", name: "Pekalongan", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Pekalongan", province: "Jawa Tengah" },
  { kind: "Kota", name: "Salatiga", province: "Jawa Tengah" },
  { kind: "Kota", name: "Tegal", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Tegal", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Banjarnegara", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Banyumas", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Batang", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Blora", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Boyolali", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Brebes", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Cilacap", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Demak", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Grobogan", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Jepara", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Karanganyar", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Kebumen", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Kendal", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Klaten", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Kudus", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Pati", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Pemalang", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Purbalingga", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Purworejo", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Rembang", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Sragen", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Sukoharjo", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Temanggung", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Wonogiri", province: "Jawa Tengah" },
  { kind: "Kabupaten", name: "Wonosobo", province: "Jawa Tengah" },

  { kind: "Kota", name: "Yogyakarta", province: "DI Yogyakarta" },
  { kind: "Kabupaten", name: "Sleman", province: "DI Yogyakarta" },
  { kind: "Kabupaten", name: "Bantul", province: "DI Yogyakarta" },
  { kind: "Kabupaten", name: "Gunungkidul", province: "DI Yogyakarta" },
  { kind: "Kabupaten", name: "Kulon Progo", province: "DI Yogyakarta" },

  { kind: "Kota", name: "Surabaya", province: "Jawa Timur" },
  { kind: "Kota", name: "Malang", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Malang", province: "Jawa Timur" },
  { kind: "Kota", name: "Batu", province: "Jawa Timur" },
  { kind: "Kota", name: "Blitar", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Blitar", province: "Jawa Timur" },
  { kind: "Kota", name: "Kediri", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Kediri", province: "Jawa Timur" },
  { kind: "Kota", name: "Madiun", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Madiun", province: "Jawa Timur" },
  { kind: "Kota", name: "Mojokerto", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Mojokerto", province: "Jawa Timur" },
  { kind: "Kota", name: "Pasuruan", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Pasuruan", province: "Jawa Timur" },
  { kind: "Kota", name: "Probolinggo", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Probolinggo", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Bangkalan", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Banyuwangi", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Bojonegoro", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Bondowoso", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Gresik", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Jember", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Jombang", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Lamongan", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Lumajang", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Magetan", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Nganjuk", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Ngawi", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Pacitan", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Pamekasan", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Ponorogo", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Sampang", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Sidoarjo", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Situbondo", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Sumenep", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Trenggalek", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Tuban", province: "Jawa Timur" },
  { kind: "Kabupaten", name: "Tulungagung", province: "Jawa Timur" },

  { kind: "Kota", name: "Serang", province: "Banten" },
  { kind: "Kabupaten", name: "Serang", province: "Banten" },
  { kind: "Kota", name: "Cilegon", province: "Banten" },
  { kind: "Kota", name: "Tangerang", province: "Banten" },
  { kind: "Kabupaten", name: "Tangerang", province: "Banten" },
  { kind: "Kota", name: "Tangerang Selatan", province: "Banten" },
  { kind: "Kabupaten", name: "Lebak", province: "Banten" },
  { kind: "Kabupaten", name: "Pandeglang", province: "Banten" },

  { kind: "Kota", name: "Denpasar", province: "Bali" },
  { kind: "Kabupaten", name: "Badung", province: "Bali" },
  { kind: "Kabupaten", name: "Gianyar", province: "Bali" },
  { kind: "Kabupaten", name: "Tabanan", province: "Bali" },
  { kind: "Kabupaten", name: "Buleleng", province: "Bali" },
  { kind: "Kabupaten", name: "Bangli", province: "Bali" },
  { kind: "Kabupaten", name: "Jembrana", province: "Bali" },
  { kind: "Kabupaten", name: "Karangasem", province: "Bali" },
  { kind: "Kabupaten", name: "Klungkung", province: "Bali" },

  { kind: "Kota", name: "Mataram", province: "Nusa Tenggara Barat" },
  { kind: "Kota", name: "Bima", province: "Nusa Tenggara Barat" },
  { kind: "Kabupaten", name: "Lombok Barat", province: "Nusa Tenggara Barat" },
  { kind: "Kabupaten", name: "Lombok Tengah", province: "Nusa Tenggara Barat" },
  { kind: "Kabupaten", name: "Lombok Timur", province: "Nusa Tenggara Barat" },
  { kind: "Kabupaten", name: "Lombok Utara", province: "Nusa Tenggara Barat" },
  { kind: "Kabupaten", name: "Sumbawa", province: "Nusa Tenggara Barat" },
  { kind: "Kabupaten", name: "Sumbawa Barat", province: "Nusa Tenggara Barat" },
  { kind: "Kabupaten", name: "Bima", province: "Nusa Tenggara Barat" },
  { kind: "Kabupaten", name: "Dompu", province: "Nusa Tenggara Barat" },

  { kind: "Kota", name: "Kupang", province: "Nusa Tenggara Timur" },
  { kind: "Kabupaten", name: "Kupang", province: "Nusa Tenggara Timur" },
  { kind: "Kabupaten", name: "Manggarai Barat", province: "Nusa Tenggara Timur" },
  { kind: "Kabupaten", name: "Manggarai", province: "Nusa Tenggara Timur" },
  { kind: "Kabupaten", name: "Ende", province: "Nusa Tenggara Timur" },
  { kind: "Kabupaten", name: "Sikka", province: "Nusa Tenggara Timur" },
  { kind: "Kabupaten", name: "Flores Timur", province: "Nusa Tenggara Timur" },
  { kind: "Kabupaten", name: "Sumba Timur", province: "Nusa Tenggara Timur" },
  { kind: "Kabupaten", name: "Alor", province: "Nusa Tenggara Timur" },

  { kind: "Kota", name: "Pontianak", province: "Kalimantan Barat" },
  { kind: "Kota", name: "Singkawang", province: "Kalimantan Barat" },
  { kind: "Kabupaten", name: "Kubu Raya", province: "Kalimantan Barat" },
  { kind: "Kabupaten", name: "Sambas", province: "Kalimantan Barat" },
  { kind: "Kabupaten", name: "Bengkayang", province: "Kalimantan Barat" },
  { kind: "Kabupaten", name: "Landak", province: "Kalimantan Barat" },
  { kind: "Kabupaten", name: "Sanggau", province: "Kalimantan Barat" },
  { kind: "Kabupaten", name: "Ketapang", province: "Kalimantan Barat" },

  { kind: "Kota", name: "Palangka Raya", province: "Kalimantan Tengah" },
  { kind: "Kabupaten", name: "Kotawaringin Barat", province: "Kalimantan Tengah" },
  { kind: "Kabupaten", name: "Kotawaringin Timur", province: "Kalimantan Tengah" },
  { kind: "Kabupaten", name: "Kapuas", province: "Kalimantan Tengah" },
  { kind: "Kabupaten", name: "Barito Utara", province: "Kalimantan Tengah" },
  { kind: "Kabupaten", name: "Murung Raya", province: "Kalimantan Tengah" },

  { kind: "Kota", name: "Banjarmasin", province: "Kalimantan Selatan" },
  { kind: "Kota", name: "Banjarbaru", province: "Kalimantan Selatan" },
  { kind: "Kabupaten", name: "Banjar", province: "Kalimantan Selatan" },
  { kind: "Kabupaten", name: "Barito Kuala", province: "Kalimantan Selatan" },
  { kind: "Kabupaten", name: "Tanah Laut", province: "Kalimantan Selatan" },
  { kind: "Kabupaten", name: "Tanah Bumbu", province: "Kalimantan Selatan" },
  { kind: "Kabupaten", name: "Kotabaru", province: "Kalimantan Selatan" },
  { kind: "Kabupaten", name: "Hulu Sungai Tengah", province: "Kalimantan Selatan" },
  { kind: "Kabupaten", name: "Tabalong", province: "Kalimantan Selatan" },

  { kind: "Kota", name: "Samarinda", province: "Kalimantan Timur" },
  { kind: "Kota", name: "Balikpapan", province: "Kalimantan Timur" },
  { kind: "Kota", name: "Bontang", province: "Kalimantan Timur" },
  { kind: "Kabupaten", name: "Kutai Kartanegara", province: "Kalimantan Timur" },
  { kind: "Kabupaten", name: "Kutai Timur", province: "Kalimantan Timur" },
  { kind: "Kabupaten", name: "Kutai Barat", province: "Kalimantan Timur" },
  { kind: "Kabupaten", name: "Penajam Paser Utara", province: "Kalimantan Timur" },
  { kind: "Kabupaten", name: "Paser", province: "Kalimantan Timur" },
  { kind: "Kabupaten", name: "Berau", province: "Kalimantan Timur" },

  { kind: "Kota", name: "Tarakan", province: "Kalimantan Utara" },
  { kind: "Kabupaten", name: "Bulungan", province: "Kalimantan Utara" },
  { kind: "Kabupaten", name: "Malinau", province: "Kalimantan Utara" },
  { kind: "Kabupaten", name: "Nunukan", province: "Kalimantan Utara" },
  { kind: "Kabupaten", name: "Tana Tidung", province: "Kalimantan Utara" },

  { kind: "Kota", name: "Manado", province: "Sulawesi Utara" },
  { kind: "Kota", name: "Bitung", province: "Sulawesi Utara" },
  { kind: "Kota", name: "Tomohon", province: "Sulawesi Utara" },
  { kind: "Kota", name: "Kotamobagu", province: "Sulawesi Utara" },
  { kind: "Kabupaten", name: "Minahasa", province: "Sulawesi Utara" },
  { kind: "Kabupaten", name: "Minahasa Utara", province: "Sulawesi Utara" },
  { kind: "Kabupaten", name: "Minahasa Selatan", province: "Sulawesi Utara" },
  { kind: "Kabupaten", name: "Minahasa Tenggara", province: "Sulawesi Utara" },
  { kind: "Kabupaten", name: "Bolaang Mongondow", province: "Sulawesi Utara" },
  { kind: "Kabupaten", name: "Kepulauan Sangihe", province: "Sulawesi Utara" },

  { kind: "Kota", name: "Gorontalo", province: "Gorontalo" },
  { kind: "Kabupaten", name: "Gorontalo", province: "Gorontalo" },
  { kind: "Kabupaten", name: "Bone Bolango", province: "Gorontalo" },
  { kind: "Kabupaten", name: "Boalemo", province: "Gorontalo" },

  { kind: "Kota", name: "Palu", province: "Sulawesi Tengah" },
  { kind: "Kabupaten", name: "Donggala", province: "Sulawesi Tengah" },
  { kind: "Kabupaten", name: "Sigi", province: "Sulawesi Tengah" },
  { kind: "Kabupaten", name: "Parigi Moutong", province: "Sulawesi Tengah" },
  { kind: "Kabupaten", name: "Banggai", province: "Sulawesi Tengah" },
  { kind: "Kabupaten", name: "Tolitoli", province: "Sulawesi Tengah" },
  { kind: "Kabupaten", name: "Poso", province: "Sulawesi Tengah" },
  { kind: "Kabupaten", name: "Morowali", province: "Sulawesi Tengah" },

  { kind: "Kota", name: "Makassar", province: "Sulawesi Selatan" },
  { kind: "Kota", name: "Parepare", province: "Sulawesi Selatan" },
  { kind: "Kota", name: "Palopo", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Gowa", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Maros", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Takalar", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Pangkajene dan Kepulauan", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Bone", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Wajo", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Soppeng", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Bulukumba", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Bantaeng", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Toraja Utara", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Tana Toraja", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Luwu", province: "Sulawesi Selatan" },
  { kind: "Kabupaten", name: "Luwu Timur", province: "Sulawesi Selatan" },

  { kind: "Kota", name: "Kendari", province: "Sulawesi Tenggara" },
  { kind: "Kota", name: "Baubau", province: "Sulawesi Tenggara" },
  { kind: "Kabupaten", name: "Konawe", province: "Sulawesi Tenggara" },
  { kind: "Kabupaten", name: "Konawe Selatan", province: "Sulawesi Tenggara" },
  { kind: "Kabupaten", name: "Kolaka", province: "Sulawesi Tenggara" },
  { kind: "Kabupaten", name: "Wakatobi", province: "Sulawesi Tenggara" },
  { kind: "Kabupaten", name: "Buton", province: "Sulawesi Tenggara" },
  { kind: "Kabupaten", name: "Muna", province: "Sulawesi Tenggara" },

  { kind: "Kota", name: "Mamuju", province: "Sulawesi Barat" },
  { kind: "Kabupaten", name: "Mamuju", province: "Sulawesi Barat" },
  { kind: "Kabupaten", name: "Majene", province: "Sulawesi Barat" },
  { kind: "Kabupaten", name: "Polewali Mandar", province: "Sulawesi Barat" },
  { kind: "Kabupaten", name: "Mamasa", province: "Sulawesi Barat" },

  { kind: "Kota", name: "Ambon", province: "Maluku" },
  { kind: "Kota", name: "Tual", province: "Maluku" },
  { kind: "Kabupaten", name: "Maluku Tengah", province: "Maluku" },
  { kind: "Kabupaten", name: "Maluku Tenggara", province: "Maluku" },
  { kind: "Kabupaten", name: "Buru", province: "Maluku" },
  { kind: "Kabupaten", name: "Kepulauan Aru", province: "Maluku" },
  { kind: "Kabupaten", name: "Seram Bagian Barat", province: "Maluku" },

  { kind: "Kota", name: "Ternate", province: "Maluku Utara" },
  { kind: "Kota", name: "Tidore Kepulauan", province: "Maluku Utara" },
  { kind: "Kabupaten", name: "Halmahera Barat", province: "Maluku Utara" },
  { kind: "Kabupaten", name: "Halmahera Utara", province: "Maluku Utara" },
  { kind: "Kabupaten", name: "Halmahera Selatan", province: "Maluku Utara" },
  { kind: "Kabupaten", name: "Pulau Morotai", province: "Maluku Utara" },

  { kind: "Kota", name: "Jayapura", province: "Papua" },
  { kind: "Kabupaten", name: "Jayapura", province: "Papua" },
  { kind: "Kabupaten", name: "Keerom", province: "Papua" },
  { kind: "Kabupaten", name: "Biak Numfor", province: "Papua" },
  { kind: "Kota", name: "Manokwari", province: "Papua Barat" },
  { kind: "Kota", name: "Sorong", province: "Papua Barat Daya" },
  { kind: "Kabupaten", name: "Sorong", province: "Papua Barat Daya" },
  { kind: "Kabupaten", name: "Raja Ampat", province: "Papua Barat Daya" },
  { kind: "Kabupaten", name: "Fakfak", province: "Papua Barat" },
  { kind: "Kabupaten", name: "Kaimana", province: "Papua Barat" },
  { kind: "Kabupaten", name: "Merauke", province: "Papua Selatan" },
  { kind: "Kabupaten", name: "Mimika", province: "Papua Tengah" },
  { kind: "Kabupaten", name: "Nabire", province: "Papua Tengah" },
  { kind: "Kabupaten", name: "Jayawijaya", province: "Papua Pegunungan" },
];

export type DomicileOption = {
  label: string;
  name: string;
  province: string;
};

export function domicileLabel(seed: DomicileSeed) {
  if (seed.kind === "Jakarta") return `${seed.name}, ${seed.province}`;
  return `${seed.kind} ${seed.name}, ${seed.province}`;
}

export const DOMICILE_OPTIONS: DomicileOption[] = SEEDS.map((seed) => ({
  label: domicileLabel(seed),
  name: seed.name,
  province: seed.province,
}));

const POPULAR = [
  "Kota Bandung, Jawa Barat",
  "Jakarta Selatan, DKI Jakarta",
  "Kota Surabaya, Jawa Timur",
  "Kota Yogyakarta, DI Yogyakarta",
  "Kota Denpasar, Bali",
  "Kota Medan, Sumatera Utara",
  "Kota Semarang, Jawa Tengah",
  "Kota Makassar, Sulawesi Selatan",
];

export function searchDomiciles(query: string, limit = 12): DomicileOption[] {
  const needle = query.trim().toLocaleLowerCase("id-ID");
  const pool = needle
    ? DOMICILE_OPTIONS.filter((option) => {
        const hay = `${option.label} ${option.name} ${option.province}`.toLocaleLowerCase("id-ID");
        return hay.includes(needle);
      })
    : POPULAR.map((label) => DOMICILE_OPTIONS.find((option) => option.label === label)).filter(
        (option): option is DomicileOption => Boolean(option),
      );
  return pool.slice(0, limit);
}
