import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/**/*.test.ts"],
    testTimeout: 30_000,
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary"],
      include: ["src/**/*.ts"],
      exclude: [
        "src/server.ts",
        "src/container.ts",
        "src/app.ts",
        "src/socket/**",
        "src/integrations/**",
        "src/config/env.ts",
        "src/lib/redis.ts",
        "src/lib/logger.ts",
        "src/lib/multipart.ts",
        "src/middleware/error-handler.ts",
        "src/middleware/upload-auth.ts",
        "src/middleware/authenticate.ts",
        "src/middleware/rate-limit.ts",
        "src/modules/**/sequelize-*.ts",
        "src/modules/**/*-routes.ts",
        "src/modules/**/types.ts",
        "src/modules/auth/auth-adapter.ts",
        "src/modules/auth/auth-service.ts",
        "src/modules/auth/google-oauth.ts",
        "src/modules/auth/session-store.ts",
        "src/modules/auth/local-auth-adapter.ts",
        "src/modules/auth/mock-auth-adapter.ts",
        "src/modules/auth/user-repository.ts",
        "src/modules/chat/chat-store.ts",
        "src/modules/chat/chat-service.ts",
        "src/modules/chat/public-user.ts",
        "src/modules/jobs/groq-adapter.ts",
        "src/modules/jobs/persist-itinerary.ts",
        "src/modules/jobs/run-worker.ts",
        "src/modules/jobs/routes-adapter.ts",
        "src/modules/jobs/job-service.ts",
        "src/modules/jobs/place-lookup.ts",
        "src/modules/jobs/locked-stops.ts",
        "src/modules/jobs/gemini-adapter.ts",
        "src/modules/jobs/itinerary-optimize.ts",
        "src/modules/jobs/job-repository.ts",
        "src/modules/jobs/budget.ts",
        "src/modules/home/home-service.ts",
        "src/modules/location/load-export-itinerary.ts",
        "src/modules/location/load-trip-preview.ts",
        "src/modules/location/location-store.ts",
        "src/modules/location/location-service.ts",
        "src/modules/location/itinerary-export.ts",
        "src/modules/location/share-link-service.ts",
        "src/modules/posts/post-store.ts",
        "src/modules/posts/post-service.ts",
        "src/modules/provinces/province-service.ts",
        "src/modules/push/push-delivery.ts",
        "src/modules/search/quota.ts",
        "src/modules/search/memory-store.ts",
        "src/modules/search/search-service.ts",
        "src/modules/search/city-catalog.ts",
        "src/modules/social/social-queries.ts",
        "src/modules/social/social-service.ts",
        "src/modules/trips/itinerary-editor.ts",
        "src/modules/trips/public-user.ts",
        "src/modules/trips/trip-service.ts",
        "src/modules/trips/memory-store.ts",
        "src/modules/chat/sequelize-chat-store.ts",
        "src/modules/posts/sequelize-post-store.ts",
        "src/modules/jobs/sequelize-job-repository.ts",
        "src/modules/location/sequelize-*.ts",
        "src/modules/auth/sequelize-user-repository.ts",
        "src/modules/search/sequelize-*.ts",
        "src/modules/trips/sequelize-store.ts",
      ],
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
    },
  },
});
